name: Run Selenium Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests with Maven
        run: mvn clean test

      - name: Upload ExtentReport as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: test-output/ExtentReport.html

      - name: Upload screenshots folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: test-output/screenshots/

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Test Report - ${{ job.status }}
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello!

            Your Selenium test run has completed on branch `${{ github.ref_name }}`.
            ✅ Status: **${{ job.status }}**
            📁 Repository: ${{ github.repository }}
            🔗 View full run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,  
            Idris GitHub Actions
